### ISSUE TITLE
Signed version in the making?

### ISSUE THREAD

**Issue by bachlipp** [bauruine/ASNumber#1]
Hi,
I was really happy with this add on. Sadly, since Mozilla forces add ons to be signed, Firefox disabled this plugin. Of course, there are workarounds like resorting to a Firefox Extended Support Release with special configuration, but it was really great if you could provide a signed update to your add on.
Cheers
Philipp

**Comment by bachlipp** [comment]
Hi,
after having been pointed to https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/ this issue turned out to be a non-issue.
Sorry for reporting it at all.
Cheers
Philipp

**Comment by bauruine** [comment]
Hi
The signing needs to be done by Mozilla only as far as i know. So if you install it from [AMO](https://addons.mozilla.org/de/firefox/addon/show-asnumber/) it should work. I just installed it on a fresh Firefox 67 and that worked. 
There was a major problem with an expired intermediate certificate that was used to sign the addons. https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/] is it possible that you are using an older version and don't have studies activated or one of the other fixes implemented? There is also a an addon that fixes the problem for older FF versions https://addons.mozilla.org/firefox/addon/disabled-add-on-fix-61-65/ which is also linked in the above blog post.

Stefan

**Comment by bauruine** [comment]
Doh just a second too late. I'm glad you could fix it.
